services:
  postgres:
    container_name: INSTANT_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - instant
    restart: unless-stopped

  auth_service:
    container_name: INSTANT_auth_service
    build: ./auth/
    ports:
      - "51756:51756"
    networks:
      - instant
    depends_on:
      - postgres
    restart: no
  
  chat_service:
    container_name: INSTANT_chat_service
    build: ./chat/
    ports:
      - "51757:51757"
    networks:
      - instant
    depends_on:
      - postgres
    restart: no

  nginx:
    container_name: INSTANT_nginx
    image: nginx
    depends_on:
      - chat_service
      - auth_service
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./website/:/usr/share/nginx/html
    networks:
      - instant
      - exposed
    restart: no

networks:
  instant:
    driver: bridge
    internal: true
  exposed:
    driver: bridge

volumes:
  postgres: