services:
  postgres:
    container_name: INSTANT_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - instant
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  instant_service:
    container_name: INSTANT_instant_service
    build: ./instant/
    ports:
      - "51756:51756"
    networks:
      - instant
    depends_on:
      postgres:
        condition: service_healthy
    restart: no

  nginx:
    container_name: INSTANT_nginx
    image: nginx
    depends_on:
      - instant_service
    ports:
      - 51757:51757
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./website/:/usr/share/nginx/html
    networks:
      - instant
    restart: no

networks:
  instant:
    driver: bridge

volumes:
  postgres: